[project]
name = "golem-py-bindings"
version = "0.1.0"
requires-python = ">=3.9"
keywords = ['datetime', 'date', 'time']
license = "Apache-2.0"
license-files = [ "../LICENSE" ]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Environment :: WebAssembly :: WASI",
    "Typing :: Typed"
]

[project.urls]
Homepage = "https://github.com/golemcloud/golem-py"
Documentation = "https://github.com/golemcloud/golem-py"
Repository = "https://github.com/golemcloud/golem-py"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "src"
module-name = "golem_py_bindings"
