[project]
name = "golem_py"
version = "0.1.0"
description = "A library that helps with writing Golem components in Python "
readme = "README.md"
requires-python = ">=3.9"
license = "Apache-2.0"
license-files = [ "LICENSE" ]
authors = [{ name = "Sébastien Eustace", email = "sebastien@eustace.io" }]
keywords = ['datetime', 'date', 'time']
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Environment :: WebAssembly :: WASI",
    "Typing :: Typed"
]

dependencies = [
    "urllib3_fork @ git+https://github.com/golemcloud/urllib3@1273c71ff7fccfdb5d1415118fa43e786b9d1818#egg=urllib3_fork"
]

[project.urls]
Homepage = "https://github.com/golemcloud/golem-py"
Documentation = "https://github.com/golemcloud/golem-py"
Repository = "https://github.com/golemcloud/golem-py"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.5"
