[project]
name = "generated-placeholder-bindings"
version = "0.1.0"
requires-python = ">=3.9"
classifiers = [
    "Private :: Do Not Upload"
]

[project.urls]
Homepage = "https://github.com/golemcloud/golem-py"
Documentation = "https://github.com/golemcloud/golem-py"
Repository = "https://github.com/golemcloud/golem-py"

[dependency-groups]
dev = [
    "componentize-py==0.16.0"
]


[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "src"
module-name = "placeholder_world"
