[project]
name = "examples"
version = "0.1.0"
requires-python = ">=3.12"
classifiers = [
    "Private :: Do Not Upload"
]
dependencies = [
    "golem-cloud"
]

[tool.uv.sources]
golem-cloud = { workspace = true }

[tool.uv]
package = false
