name: CI

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  pull_request:

jobs:
  check:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Check format
        run: uv run ruff check

      - name: Check the project builds
        run: uv build --all-packages

      - name: Run tests
        run: uv run pytest --junit-xml=test-results.xml tests

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "test-results.xml tests"
          detailed_summary: true
          include_passed: true

  publish:
    name: publish main package
    needs: [check]
    if: "startsWith(github.ref, 'refs/tags/v')"
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - id: get_version
        name: Get the version
        uses: battila7/get-version-action@v2

      - name: Set version for the uv project
        run: uv version ${{ steps.get_version.outputs.version-without-v }}

      - name: Build the project
        run: uv build --package golem-cloud

      - name: Publish to pypi
        run: uv publish
