[project]
name = "golem-cloud-bindings-dev"
version = "0.1.1"
requires-python = ">=3.12"
classifiers = [
    "Private :: Do Not Upload"
]
dependencies = [
    "componentize-py==0.16.0"
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "src"
module-name = "golem_cloud_bindings"
